# Enable C++ support
language: cpp

addons:
  apt:
    packages:
      - cmake
      - libgsl0-dev
      - libfftw3-3
      - libccfits-dev
      - libnfft3-dev
      - libarmadillo-dev
      - libboost-all-dev
  homebrew:
    packages: &macos_packages
      - cmake
      - pkgconfig
      - gsl
      - fftw
      - brewsci/science/ccfits
      - cfitsio
      - brewsci/science/nfft
      - armadillo

matrix:
  include:
    - os: linux
    - os: osx
      osx_image: xcode10.1
      env:
        - MATRIX_EVAL="brew uninstall --ignore-dependencies boost && brew install boost --cc=gcc-7 && CC=gcc-7 && CXX=g++-7"
      addons:
        homebrew:
          packages:
            - gcc@7
            - *macos_packages
    - os: osx
      osx_image: xcode10.1
      env:
        - MATRIX_EVAL="CC=/usr/local/opt/llvm/bin/clang && CXX=/usr/local/opt/llvm/bin/clang++"
      addons:
        homebrew:
          packages:
            - llvm
            - libomp
            - boost
            - *macos_packages

cache:
    directories:
      - /home/travis/build/CosmoStat/Glimpse/build/SPARSE2D
      - /home/travis/build/CosmoStat/Glimpse/build/NICAEA

before_install:
  - eval "${MATRIX_EVAL}"

install: true

# Build steps
script:
    - mkdir -p build && cd build
    - cmake ..
    - make
    - ./glimpse --version
